[build]
  command = "echo 'No build required'"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/setup-db"
  to = "/.netlify/functions/db-setup"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
